jenkins:
  systemMessage: "<div style='border-radius:10px; text-align: center; padding:20px; font-size:160%; background-color: tomato;'>Jenkins configured automatically by Jenkins Configuration as Code plugin</div><br>"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  globalNodeProperties:
  - envVars:
      env:
      - key: "EMAIL"
        value: ${EMAIL}

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: github_ssh
              username: vladislav
              description: "SSH Github"
              privateKeySource:
                directEntry:
                  privateKey: ${github_ssh}
          - string:
              scope: GLOBAL
              id: "accessKey"
              secret: "${accessKey}"
              description: "aws accessKey"
          - string:
              scope: GLOBAL
              id: "secretKey"
              secret: "${secretKey}"
              description: "aws secretKey"
          - usernamePassword:
              id: "dockerhub"
              password: ${dockerhub_token}
              scope: GLOBAL
              username: "vlemi"
          - usernamePassword:
              id: "email"
              password: ${email_app_pass}
              scope: GLOBAL
              username: "phaeton.vlm@gmail.com"
          - usernamePassword:
              id: "github_ssh2"
              password: "{AQAAABAAAAAw5OYIknqCQQvGHuUkcdSSS3Xc+tgfVfaQU8NeZAn8pMv/rff7FDNdThuhpZ0fkeCyQaTLhysLCu+y1PwNjGFgrQ==}"
              scope: GLOBAL
              username: "user"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"

unclassified:
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    allowedDomains: "@gmail.com"
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultRecipients: ${EMAIL}
    defaultReplyTo: ${EMAIL}
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultSuffix: "@gmail.com"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    listId: ${EMAIL}
    mailAccount:
      credentialsId: "email"
      smtpHost: "smtp.gmail.com"
      smtpPort: "465"
      useSsl: true
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false

jobs:
  - file: /var/jenkins_home/casc_configs/seedjob.groovy

  