jenkins:
  systemMessage: "<div style='border-radius:10px; text-align: center; padding:20px; font-size:160%; background-color: tomato;'>Jenkins configured automatically by Jenkins Configuration as Code plugin</div><br>"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: github_ssh
              username: vladislav
              description: "SSH Github"
              privateKeySource:
                directEntry:
                  privateKey: ${github_ssh}
          - string:
              scope: GLOBAL
              id: "accessKey"
              secret: "${accessKey}"
              description: "aws accessKey"
          - string:
              scope: GLOBAL
              id: "secretKey"
              secret: "${secretKey}"
              description: "aws secretKey"
          - usernamePassword:
              id: "dockerhub"
              password: ${dockerhub_token}
              scope: GLOBAL
              username: "vlemi"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"

unclassified:
  mailer:
      authentication:
        password: ${EMAIL_PASSWORD}
        username: ${EMAIL}
      charset: "UTF-8"
      defaultSuffix: "@gmail.com"
      smtpHost: "smtp.gmail.com"
      smtpPort: "465"
      useSsl: true
      useTls: false

jobs:
  - file: /var/jenkins_home/casc_configs/seedjob.groovy

  