version: '3.9'
services:
  jenkins-server:  
    image: vlemi/jenkins-server:v2
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      EMAIL: ${EMAIL}
      DOCKER_HOST: tcp://jenkins-docker:2375
      DOCKER_CERT_PATH: ""
      DOCKER_TLS_VERIFY: ""
    secrets:
      - email_app_pass
      - dockerhub_token
      - github_ssh
      - accessKey
      - secretKey
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/ubuntu/jenkins/casc_configs:/var/jenkins_home/casc_configs/
    networks:
      - jenkins-network
    depends_on:
      - jenkins-docker

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network
 
volumes:
  jenkins-data:

networks:
  jenkins-network:

secrets:
  github_ssh:
    file: /home/ubuntu/.ssh/id_rsa
  accessKey:
    file: /home/ubuntu/.aws_cred/aws_access_key_id
  secretKey:
    file: /home/ubuntu/.aws_cred/aws_secret_access_key
  dockerhub_token:
    file: /home/ubuntu/.ssh/dockerhub_token
  email_app_pass:
    file: /home/ubuntu/.ssh/app_password
