apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: t2.medium
  #   desiredCapacity: 1
  #   volumeSize: 50
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']