apiVersion: v1
kind: Service
metadata:
  name: todoapp-s-node
spec:
  selector:
    app: tododapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
      nodePort: 32000
  type: NodePort
