apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig  
metadata:
  name: demo-cluster
  region: us-east-1

vpc:
  cidr: 192.168.0.0/16
  # nat:
  #   gateway: HighlyAvailable

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    volumeSize: 80
    # ssh:
    #   allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: t2.medium
  #   desiredCapacity: 1
  #   volumeSize: 50
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d"]

# cloudWatch:
#   clusterLogging:
#     # enable specific types of cluster control plane logs
#     enableTypes: ["*"]
#     # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
#     # supported special values: "*" and "all"

#     # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
#     # By default, log data is stored in CloudWatch Logs indefinitely.
#     logRetentionInDays: 1